quarkus.artemis.password=artemis
quarkus.artemis.username=artemis
quarkus.artemis.url=tcp://oravm05:61616

ibm.mq.host=oravm05
ibm.mq.port=1414
ibm.mq.channel=DEV.APP.SVRCONN
ibm.mq.queueManagerName=QM1
ibm.mq.username=app
ibm.mq.password=passw0rd

quarkus.log.category.uppercaseTransformation.level=INFO
quarkus.log.category.extractBodyTransformation.level=INFO
quarkus.log.category.wrapbodyTransformation.level=INFO

quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=postgres
quarkus.datasource.password=postgres
quarkus.datasource.jdbc.url=jdbc:postgresql://oravm05:5432/postgres
quarkus.datasource.jdbc.max-size=16

app.agent.config.id=agent1
app.agent.config.version=2.0

quarkus.kubernetes.idempotent=true
quarkus.container-image.registry=ghcr.io
quarkus.container-image.group=rmortale
#quarkus.container-image.tag=main

