apiVersion: v1
data:
  application.properties: |

    quarkus.log.category.uppercaseTransformation.level=INFO
    quarkus.log.category.extractBodyTransformation.level=INFO
    quarkus.log.category.wrapbodyTransformation.level=INFO

    app.agent.config.id=agent1
    app.agent.config.version=3.0

kind: ConfigMap
metadata:
  name: quarkus-jdbc-paramsource-config
