apiVersion: apps/v1
kind: Deployment
metadata:
  name: quarkus-jdbc-paramsource
spec:
  template:
    spec:
      containers:
        - name: quarkus-jdbc-paramsource
          env:
            - name: APP_AGENT_CONFIG_ID
              value: "agent2"
            - name: APP_AGENT_CONFIG_VERSION
              value: "2.0"
