apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: quarkus-jdbc-paramsource-devt
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s
    directory:
      include: '*.yml'
    repoURL: https://github.com/rmortale/quarkus-jdbc-paramsource.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true