apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
  name: quarkus-jdbc-paramsource-acpt
  namespace: argocd
spec:
  destination:
    namespace: acpt
    server: https://kubernetes.default.svc
  project: default
  source:
    path: k8s/overlays/acpt
    repoURL: https://github.com/rmortale/quarkus-jdbc-paramsource.git
    targetRevision: main
